{
  "cameraConfig": {
    "cameraType": "INTEL_REALSENSE",
    "originalResolution": {
      "x": 960,
      "y": 540
    },
    "fps": 60,
    "exposure": 100.0,
    "gain": 70,
    "brightness": 30,
    "contrast": 50,
    "gamma": 400,
    "hue": 0,
    "saturation": 70,
    "sharpness": 100,
    "white_balance": 4000
  },
  "preprocessConfig": {
    "sourceRegion": {
      "lowerLeft": {
        "x": 86,
        "y": 467
      },
      "upperLeft": {
        "x": 66,
        "y": 65
      },
      "lowerRight": {
        "x": 845,
        "y": 440
      },
      "upperRight": {
        "x": 852,
        "y": 61
      }
    },
    "translateResolution": {
      "x": 800,
      "y": 400
    },
    "doTranslation": true
  },
  "detectMotion": true
}
