# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_config.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera_config.proto',
  package='wadjet',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63\x61mera_config.proto\x12\x06wadjet\"\"\n\nResolution\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x97\x01\n\x07Region4\x12!\n\nlower_left\x18\x01 \x01(\x0b\x32\r.wadjet.Point\x12!\n\nupper_left\x18\x02 \x01(\x0b\x32\r.wadjet.Point\x12\"\n\x0blower_right\x18\x03 \x01(\x0b\x32\r.wadjet.Point\x12\"\n\x0bupper_right\x18\x04 \x01(\x0b\x32\r.wadjet.Point\"w\n\x11\x44\x65pthSensorConfig\x12/\n\x13original_resolution\x18\x01 \x01(\x0b\x32\x12.wadjet.Resolution\x12\x0b\n\x03\x66ps\x18\x02 \x01(\x05\x12\x11\n\tmin_range\x18\x03 \x01(\x02\x12\x11\n\tmax_range\x18\x04 \x01(\x02\"\x96\x03\n\x0c\x43\x61meraConfig\x12\x34\n\x0b\x63\x61mera_type\x18\x01 \x01(\x0e\x32\x1f.wadjet.CameraConfig.CameraType\x12\x15\n\rcamera_source\x18\x02 \x01(\x05\x12/\n\x13original_resolution\x18\x03 \x01(\x0b\x32\x12.wadjet.Resolution\x12\x0b\n\x03\x66ps\x18\x04 \x01(\x05\x12\x10\n\x08\x65xposure\x18\x05 \x01(\x02\x12\x0c\n\x04gain\x18\x06 \x01(\x02\x12\x12\n\nbrightness\x18\x07 \x01(\x02\x12\x10\n\x08\x63ontrast\x18\x08 \x01(\x02\x12\r\n\x05gamma\x18\t \x01(\x02\x12\x0b\n\x03hue\x18\n \x01(\x02\x12\x12\n\nsaturation\x18\x0b \x01(\x02\x12\x11\n\tsharpness\x18\x0c \x01(\x02\x12\x15\n\rwhite_balance\x18\r \x01(\x02\x12/\n\x0c\x64\x65pth_config\x18\x1e \x01(\x0b\x32\x19.wadjet.DepthSensorConfig\"*\n\nCameraType\x12\x07\n\x03USB\x10\x00\x12\x13\n\x0fINTEL_REALSENSE\x10\x01\"\x84\x01\n\x10PreprocessConfig\x12&\n\rsource_region\x18\n \x01(\x0b\x32\x0f.wadjet.Region4\x12\x30\n\x14translate_resolution\x18\x0b \x01(\x0b\x32\x12.wadjet.Resolution\x12\x16\n\x0e\x64o_translation\x18\x0c \x01(\x08\"\x89\x01\n\x0e\x43\x61pturerConfig\x12+\n\rcamera_config\x18\x01 \x01(\x0b\x32\x14.wadjet.CameraConfig\x12\x33\n\x11preprocess_config\x18\x02 \x01(\x0b\x32\x18.wadjet.PreprocessConfig\x12\x15\n\rdetect_motion\x18\n \x01(\x08'
)



_CAMERACONFIG_CAMERATYPE = _descriptor.EnumDescriptor(
  name='CameraType',
  full_name='wadjet.CameraConfig.CameraType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USB', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTEL_REALSENSE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=738,
  serialized_end=780,
)
_sym_db.RegisterEnumDescriptor(_CAMERACONFIG_CAMERATYPE)


_RESOLUTION = _descriptor.Descriptor(
  name='Resolution',
  full_name='wadjet.Resolution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='wadjet.Resolution.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='wadjet.Resolution.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=65,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='wadjet.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='wadjet.Point.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='wadjet.Point.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=96,
)


_REGION4 = _descriptor.Descriptor(
  name='Region4',
  full_name='wadjet.Region4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lower_left', full_name='wadjet.Region4.lower_left', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper_left', full_name='wadjet.Region4.upper_left', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lower_right', full_name='wadjet.Region4.lower_right', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upper_right', full_name='wadjet.Region4.upper_right', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=250,
)


_DEPTHSENSORCONFIG = _descriptor.Descriptor(
  name='DepthSensorConfig',
  full_name='wadjet.DepthSensorConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='original_resolution', full_name='wadjet.DepthSensorConfig.original_resolution', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fps', full_name='wadjet.DepthSensorConfig.fps', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_range', full_name='wadjet.DepthSensorConfig.min_range', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_range', full_name='wadjet.DepthSensorConfig.max_range', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=371,
)


_CAMERACONFIG = _descriptor.Descriptor(
  name='CameraConfig',
  full_name='wadjet.CameraConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_type', full_name='wadjet.CameraConfig.camera_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='camera_source', full_name='wadjet.CameraConfig.camera_source', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='original_resolution', full_name='wadjet.CameraConfig.original_resolution', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fps', full_name='wadjet.CameraConfig.fps', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exposure', full_name='wadjet.CameraConfig.exposure', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gain', full_name='wadjet.CameraConfig.gain', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='brightness', full_name='wadjet.CameraConfig.brightness', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contrast', full_name='wadjet.CameraConfig.contrast', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamma', full_name='wadjet.CameraConfig.gamma', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hue', full_name='wadjet.CameraConfig.hue', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='saturation', full_name='wadjet.CameraConfig.saturation', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sharpness', full_name='wadjet.CameraConfig.sharpness', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='white_balance', full_name='wadjet.CameraConfig.white_balance', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth_config', full_name='wadjet.CameraConfig.depth_config', index=13,
      number=30, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CAMERACONFIG_CAMERATYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=780,
)


_PREPROCESSCONFIG = _descriptor.Descriptor(
  name='PreprocessConfig',
  full_name='wadjet.PreprocessConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_region', full_name='wadjet.PreprocessConfig.source_region', index=0,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='translate_resolution', full_name='wadjet.PreprocessConfig.translate_resolution', index=1,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='do_translation', full_name='wadjet.PreprocessConfig.do_translation', index=2,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=783,
  serialized_end=915,
)


_CAPTURERCONFIG = _descriptor.Descriptor(
  name='CapturerConfig',
  full_name='wadjet.CapturerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_config', full_name='wadjet.CapturerConfig.camera_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preprocess_config', full_name='wadjet.CapturerConfig.preprocess_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detect_motion', full_name='wadjet.CapturerConfig.detect_motion', index=2,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=918,
  serialized_end=1055,
)

_REGION4.fields_by_name['lower_left'].message_type = _POINT
_REGION4.fields_by_name['upper_left'].message_type = _POINT
_REGION4.fields_by_name['lower_right'].message_type = _POINT
_REGION4.fields_by_name['upper_right'].message_type = _POINT
_DEPTHSENSORCONFIG.fields_by_name['original_resolution'].message_type = _RESOLUTION
_CAMERACONFIG.fields_by_name['camera_type'].enum_type = _CAMERACONFIG_CAMERATYPE
_CAMERACONFIG.fields_by_name['original_resolution'].message_type = _RESOLUTION
_CAMERACONFIG.fields_by_name['depth_config'].message_type = _DEPTHSENSORCONFIG
_CAMERACONFIG_CAMERATYPE.containing_type = _CAMERACONFIG
_PREPROCESSCONFIG.fields_by_name['source_region'].message_type = _REGION4
_PREPROCESSCONFIG.fields_by_name['translate_resolution'].message_type = _RESOLUTION
_CAPTURERCONFIG.fields_by_name['camera_config'].message_type = _CAMERACONFIG
_CAPTURERCONFIG.fields_by_name['preprocess_config'].message_type = _PREPROCESSCONFIG
DESCRIPTOR.message_types_by_name['Resolution'] = _RESOLUTION
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Region4'] = _REGION4
DESCRIPTOR.message_types_by_name['DepthSensorConfig'] = _DEPTHSENSORCONFIG
DESCRIPTOR.message_types_by_name['CameraConfig'] = _CAMERACONFIG
DESCRIPTOR.message_types_by_name['PreprocessConfig'] = _PREPROCESSCONFIG
DESCRIPTOR.message_types_by_name['CapturerConfig'] = _CAPTURERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Resolution = _reflection.GeneratedProtocolMessageType('Resolution', (_message.Message,), {
  'DESCRIPTOR' : _RESOLUTION,
  '__module__' : 'camera_config_pb2'
  # @@protoc_insertion_point(class_scope:wadjet.Resolution)
  })
_sym_db.RegisterMessage(Resolution)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'camera_config_pb2'
  # @@protoc_insertion_point(class_scope:wadjet.Point)
  })
_sym_db.RegisterMessage(Point)

Region4 = _reflection.GeneratedProtocolMessageType('Region4', (_message.Message,), {
  'DESCRIPTOR' : _REGION4,
  '__module__' : 'camera_config_pb2'
  # @@protoc_insertion_point(class_scope:wadjet.Region4)
  })
_sym_db.RegisterMessage(Region4)

DepthSensorConfig = _reflection.GeneratedProtocolMessageType('DepthSensorConfig', (_message.Message,), {
  'DESCRIPTOR' : _DEPTHSENSORCONFIG,
  '__module__' : 'camera_config_pb2'
  # @@protoc_insertion_point(class_scope:wadjet.DepthSensorConfig)
  })
_sym_db.RegisterMessage(DepthSensorConfig)

CameraConfig = _reflection.GeneratedProtocolMessageType('CameraConfig', (_message.Message,), {
  'DESCRIPTOR' : _CAMERACONFIG,
  '__module__' : 'camera_config_pb2'
  # @@protoc_insertion_point(class_scope:wadjet.CameraConfig)
  })
_sym_db.RegisterMessage(CameraConfig)

PreprocessConfig = _reflection.GeneratedProtocolMessageType('PreprocessConfig', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSCONFIG,
  '__module__' : 'camera_config_pb2'
  # @@protoc_insertion_point(class_scope:wadjet.PreprocessConfig)
  })
_sym_db.RegisterMessage(PreprocessConfig)

CapturerConfig = _reflection.GeneratedProtocolMessageType('CapturerConfig', (_message.Message,), {
  'DESCRIPTOR' : _CAPTURERCONFIG,
  '__module__' : 'camera_config_pb2'
  # @@protoc_insertion_point(class_scope:wadjet.CapturerConfig)
  })
_sym_db.RegisterMessage(CapturerConfig)


# @@protoc_insertion_point(module_scope)
